model:
  # ae_model:
  #   target: DDPM.Models.auto_encoder.AE
  #   params:
  #     in_dim: 144
  #     hidden_size_sqrt: 8
  #     dp_ratio: 0.2

  diffusion:
    target: DDPM.Models.gaussian_diffusion.GaussianDiffusion
    params:
      model_config:
        target: DDPM.Models.u_net_conv3d.Unet
        params:
          dim: 32
          init_dim: 16
          out_dim: 1
          dim_mults: [1, 2, 2]
          channels: 1
          resnet_block_groups: 8
          image_size: 12
          window: 12
          self_condition: False

      timesteps: 200
      sampling_timesteps: 100
      loss_type: l1
      objective: pred_x0
      beta_schedule: cosine
      
solver:
  base_lr: 1.0e-5
  max_epochs: 15000
  results_folder: ./Checkpoints_abilene_dm
  gradient_accumulate_every: 2
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: DDPM.Engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 5000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  batch_size: 128
  test_size: 512

inference:
  sample_size: 3000
  single_size: 1500
  guidance_lr: 0.05
  use_em: True
